services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /mnt/main/AppData/CodeServer/config:/config
    ports:
      - 8443:8443
      - 1593:1593
    restart: unless-stopped
networks: {}