version: "3"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - 54:54/tcp
      - 54:54/udp
      - 68:68/udp # Only required if you are using Pi-hole as your DHCP server
      - 82:82/tcp
    environment:
      TZ: America/Los_angeles
      # WEBPASSWORD: 'set a secure password here or it will be random'
      # Volumes store your data between container upgrades
    volumes:
      - /mnt/main/AppData/PiHole/etc-pihole:/etc/pihole
      - /mnt/main/AppData/PiHole/etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
networks: {}